config/routes.rb
Rails.application.routes.draw do
  resources :appeals
  resources :license_results
  resources :exam_settings
  resources :passing_marks
  resources :applicant_types
  resources :exam_types
  resources :placements do
    collection do
      get 'match'
      get 'publish'
      get 'clear'
      get 'statistics'
    end
  end
  resources :settings
  resources :exams do
    collection do
      get 'import_exam'
      post 'import_exam'
      get 'import_interview'
      post 'import_interview'
      get 'exam_detail'
    end
  end
  resources :timers, path: 'countdown' do
    collection do
      get 'load_deadline'
    end
  end
  resources :application_instructions
  resources :applicant_exam_hubs
  resources :exam_hubs
  resources :regions
  resources :match_results
  resources :events
  resources :academic_years
  resources :universities
  resources :programs
  resources :applicants do
    collection do
      get 'import_applicants'
      post 'import_applicants'
      get 'instructions'
      get 'load_other_university'
      get 'load_disability'
      get 'licensing'
      get 'grade'
      get 'load_attachments'
      get 'university_applicants_by_program'
      get 'applicants_by_program_by_university'
      get 'university_applicants_status_by_program'
      get 'applicants_status'
      get 'publish'
      get 'check_exam'
    end
    member do
      get 'details'
      get 'submit'
    end
  end
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  scope "/admin" do
    resources :users do
      member do
        get 'confirm'
      end
      collection do
        get 'load_institutions'
      end
    end
  end

  authenticated :user do
    root 'home#index', as: :authenticated_root
  end
  get 'home/index'
  get 'home/check_exam_result'
  root to: 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/applicant_exam_hub.rb
class ApplicantExamHub < ApplicationRecord
  belongs_to :applicant
  belongs_to :exam_hub

  validates :exam_hub_id, presence: true
  validate :validate_ceiling

  def validate_ceiling
    if exam_hub.total_applicants.reject{ |a| a == self.applicant}.count >= exam_hub.ceiling
      errors.add('exam_hub_id', 'is already full, please select another exam hub')
    end
  end

  def to_s
    exam_hub
  end
end

app/controllers/applicant_exam_hubs_controller.rb
class ApplicantExamHubsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
  before_action :set_applicant_exam_hub, only: [:show, :edit, :update, :destroy]

  # GET /applicant_exam_hubs
  # GET /applicant_exam_hubs.json
  def index
    @applicant_exam_hubs = ApplicantExamHub.all
  end

  # GET /applicant_exam_hubs/1
  # GET /applicant_exam_hubs/1.json
  def show
  end

  # GET /applicant_exam_hubs/new
  def new
    @applicant_exam_hub = ApplicantExamHub.new
    @applicant = current_user.applicant
  end

  # GET /applicant_exam_hubs/1/edit
  def edit
    @applicant = @applicant_exam_hub.applicant
  end

  # POST /applicant_exam_hubs
  # POST /applicant_exam_hubs.json
  def create
    @applicant_exam_hub = ApplicantExamHub.new(applicant_exam_hub_params)
    @applicant  = @applicant_exam_hub.applicant
    respond_to do |format|
      if @applicant_exam_hub.save
        format.html { redirect_to new_applicant_declaration_path, notice: 'Exam hub was successfully created.' }
        format.json { render :show, status: :created, location: @applicant_exam_hub }
      else
        format.html { render :new }
        format.json { render json: @applicant_exam_hub.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /applicant_exam_hubs/1
  # PATCH/PUT /applicant_exam_hubs/1.json
  def update
    @applicant  = @applicant_exam_hub.applicant
    respond_to do |format|
      if @applicant_exam_hub.update(applicant_exam_hub_params)
        if @applicant.applicant_declaration.blank?
          format.html { redirect_to new_applicant_declaration_path, notice: 'Exam hub was successfully updated.' }
        else
          format.html { redirect_to edit_applicant_declaration_path(@applicant.applicant_declaration), notice: 'Exam hub was successfully updated.' }
        end
        format.json { render :show, status: :ok, location: @applicant_exam_hub }
      else
        format.html { render :edit }
        format.json { render json: @applicant_exam_hub.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /applicant_exam_hubs/1
  # DELETE /applicant_exam_hubs/1.json
  def destroy
    @applicant_exam_hub.destroy
    respond_to do |format|
      format.html { redirect_to applicant_exam_hubs_url, notice: 'Applicant exam hub was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_applicant_exam_hub
      @applicant_exam_hub = ApplicantExamHub.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def applicant_exam_hub_params
      params.require(:applicant_exam_hub).permit(:applicant_id, :exam_hub_id)
    end
end

app/helpers/applicant_exam_hubs_helper.rb
module ApplicantExamHubsHelper
end

app/views/applicant_exam_hubs/_form.html.erb
<%= simple_form_for(@applicant_exam_hub) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs applicant_exam_hub">
    <%= f.input :applicant_id, as: :hidden, input_html: {value: @applicant.id} %>
    <label>Where Do you want to take the entrance exam ?</label><br/>
    <%= f.collection_radio_buttons :exam_hub_id, ExamHub.all, :id, :name %>
    <%= f.full_error :exam_hub_id %>
  </div>
  <hr/>
  <div class="form-actions">
    <%= f.button :submit, 'Save and Continue' %>
  </div>
<% end %>

app/views/applicant_exam_hubs/edit.html.erb
<%= render partial: 'form', layout: 'layouts/form_layout', locals: { title: "Edit Exam Hub" } %>

app/views/applicant_exam_hubs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Applicant Exam Hubs</h1>

<table>
  <thead>
    <tr>
      <th>Applicant</th>
      <th>Exam hub</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @applicant_exam_hubs.each do |applicant_exam_hub| %>
      <tr>
        <td><%= applicant_exam_hub.applicant %></td>
        <td><%= applicant_exam_hub.exam_hub %></td>
        <td><%= link_to 'Show', applicant_exam_hub %>
        <%= link_to 'Edit', edit_applicant_exam_hub_path(applicant_exam_hub) %>
        <%= link_to 'Destroy', applicant_exam_hub, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Applicant Exam Hub', new_applicant_exam_hub_path %>

app/views/applicant_exam_hubs/new.html.erb
<%= render partial: 'form', layout: 'layouts/form_layout', locals: { title: "Select Exam Hub" } %>

app/views/applicant_exam_hubs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Applicant:</strong>
  <%= @applicant_exam_hub.applicant %>
</p>

<p>
  <strong>Exam hub:</strong>
  <%= @applicant_exam_hub.exam_hub %>
</p>

<%= link_to 'Edit', edit_applicant_exam_hub_path(@applicant_exam_hub) %> |
<%= link_to 'Back', applicant_exam_hubs_path %>