config/routes.rb
Rails.application.routes.draw do
  resources :appeals
  resources :license_results
  resources :exam_settings
  resources :passing_marks
  resources :applicant_types
  resources :exam_types
  resources :placements do
    collection do
      get 'match'
      get 'publish'
      get 'clear'
      get 'statistics'
    end
  end
  resources :settings
  resources :exams do
    collection do
      get 'import_exam'
      post 'import_exam'
      get 'import_interview'
      post 'import_interview'
      get 'exam_detail'
    end
  end
  resources :timers, path: 'countdown' do
    collection do
      get 'load_deadline'
    end
  end
  resources :application_instructions
  resources :applicant_exam_hubs
  resources :exam_hubs
  resources :regions
  resources :match_results
  resources :events
  resources :academic_years
  resources :universities
  resources :programs
  resources :applicants do
    collection do
      get 'import_applicants'
      post 'import_applicants'
      get 'instructions'
      get 'load_other_university'
      get 'load_disability'
      get 'licensing'
      get 'grade'
      get 'load_attachments'
      get 'university_applicants_by_program'
      get 'applicants_by_program_by_university'
      get 'university_applicants_status_by_program'
      get 'applicants_status'
      get 'publish'
      get 'check_exam'
    end
    member do
      get 'details'
      get 'submit'
    end
  end
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  scope "/admin" do
    resources :users do
      member do
        get 'confirm'
      end
      collection do
        get 'load_institutions'
      end
    end
  end

  authenticated :user do
    root 'home#index', as: :authenticated_root
  end
  get 'home/index'
  get 'home/check_exam_result'
  root to: 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/license_result.rb
class LicenseResult < ApplicationRecord
  belongs_to :applicant

  def publish_status
    published? ? 'Published' : 'Not Published'
  end
end

app/controllers/license_results_controller.rb
class LicenseResultsController < ApplicationController
  before_action :set_license_result, only: [:show, :edit, :update, :destroy]

  # GET /license_results
  # GET /license_results.json
  def index
    @license_results = LicenseResult.all
  end

  # GET /license_results/1
  # GET /license_results/1.json
  def show
  end

  # GET /license_results/new
  def new
    @license_result = LicenseResult.new
  end

  # GET /license_results/1/edit
  def edit
  end

  # POST /license_results
  # POST /license_results.json
  def create
    @license_result = LicenseResult.new(license_result_params)

    respond_to do |format|
      if @license_result.save
        format.html { redirect_to @license_result, notice: 'License result was successfully created.' }
        format.json { render :show, status: :created, location: @license_result }
      else
        format.html { render :new }
        format.json { render json: @license_result.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /license_results/1
  # PATCH/PUT /license_results/1.json
  def update
    respond_to do |format|
      if @license_result.update(license_result_params)
        format.html { redirect_to @license_result, notice: 'License result was successfully updated.' }
        format.json { render :show, status: :ok, location: @license_result }
      else
        format.html { render :edit }
        format.json { render json: @license_result.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /license_results/1
  # DELETE /license_results/1.json
  def destroy
    @license_result.destroy
    respond_to do |format|
      format.html { redirect_to license_results_url, notice: 'License result was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_license_result
      @license_result = LicenseResult.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def license_result_params
      params.require(:license_result).permit(:applicant_id, :result)
    end
end

app/helpers/license_results_helper.rb
module LicenseResultsHelper
end

app/views/license_results/_form.html.erb
<%= simple_form_for(@license_result) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :applicant %>
    <%= f.input :result %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/license_results/edit.html.erb
<h1>Editing License Result</h1>

<%= render 'form', license_result: @license_result %>

<%= link_to 'Show', @license_result %> |
<%= link_to 'Back', license_results_path %>

app/views/license_results/index.html.erb
<div class="header">
  <h2>
    License Results
  </h2>
</div>
<div class="body table-responsive">
  <table class="table table-bordered table-striped table-hover dataTable js-exportable">
  <thead>
    <tr>
      <th>Applicant</th>
      <th>Result</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @license_results.each do |license_result| %>
      <tr>
        <td><%= license_result.applicant %></td>
        <td><%= license_result.result %></td>
        <td><%= link_to 'Show', license_result %></td>
        <td><%= link_to 'Edit', edit_license_result_path(license_result) %></td>
        <td><%= link_to 'Destroy', license_result, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
  <br/>

<%= link_to 'New License Result', new_license_result_path %>
</div>

app/views/license_results/new.html.erb
<h1>New License Result</h1>

<%= render 'form', license_result: @license_result %>

<%= link_to 'Back', license_results_path %>

app/views/license_results/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Applicant:</strong>
  <%= @license_result.applicant %>
</p>

<p>
  <strong>Result:</strong>
  <%= @license_result.result %>
</p>

<%= link_to 'Edit', edit_license_result_path(@license_result) %> |
<%= link_to 'Back', license_results_path %>