config/routes.rb
Rails.application.routes.draw do
  resources :appeals
  resources :license_results
  resources :exam_settings
  resources :passing_marks
  resources :applicant_types
  resources :exam_types
  resources :placements do
    collection do
      get 'match'
      get 'publish'
      get 'clear'
      get 'statistics'
    end
  end
  resources :settings
  resources :exams do
    collection do
      get 'import_exam'
      post 'import_exam'
      get 'import_interview'
      post 'import_interview'
      get 'exam_detail'
    end
  end
  resources :timers, path: 'countdown' do
    collection do
      get 'load_deadline'
    end
  end
  resources :application_instructions
  resources :applicant_exam_hubs
  resources :exam_hubs
  resources :regions
  resources :match_results
  resources :events
  resources :academic_years
  resources :universities
  resources :programs
  resources :applicants do
    collection do
      get 'import_applicants'
      post 'import_applicants'
      get 'instructions'
      get 'load_other_university'
      get 'load_disability'
      get 'licensing'
      get 'grade'
      get 'load_attachments'
      get 'university_applicants_by_program'
      get 'applicants_by_program_by_university'
      get 'university_applicants_status_by_program'
      get 'applicants_status'
      get 'publish'
      get 'check_exam'
    end
    member do
      get 'details'
      get 'submit'
    end
  end
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  scope "/admin" do
    resources :users do
      member do
        get 'confirm'
      end
      collection do
        get 'load_institutions'
      end
    end
  end

  authenticated :user do
    root 'home#index', as: :authenticated_root
  end
  get 'home/index'
  get 'home/check_exam_result'
  root to: 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/applicant_types_controller.rb
class ApplicantTypesController < ApplicationController
  before_action :set_applicant_type, only: [:show, :edit, :update, :destroy]

  # GET /applicant_types
  # GET /applicant_types.json
  def index
    @applicant_types = ApplicantType.all
  end

  # GET /applicant_types/1
  # GET /applicant_types/1.json
  def show
  end

  # GET /applicant_types/new
  def new
    @applicant_type = ApplicantType.new
  end

  # GET /applicant_types/1/edit
  def edit
  end

  # POST /applicant_types
  # POST /applicant_types.json
  def create
    @applicant_type = ApplicantType.new(applicant_type_params)

    respond_to do |format|
      if @applicant_type.save
        format.html { redirect_to @applicant_type, notice: 'Applicant type was successfully created.' }
        format.json { render :show, status: :created, location: @applicant_type }
      else
        format.html { render :new }
        format.json { render json: @applicant_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /applicant_types/1
  # PATCH/PUT /applicant_types/1.json
  def update
    respond_to do |format|
      if @applicant_type.update(applicant_type_params)
        format.html { redirect_to @applicant_type, notice: 'Applicant type was successfully updated.' }
        format.json { render :show, status: :ok, location: @applicant_type }
      else
        format.html { render :edit }
        format.json { render json: @applicant_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /applicant_types/1
  # DELETE /applicant_types/1.json
  def destroy
    @applicant_type.destroy
    respond_to do |format|
      format.html { redirect_to applicant_types_url, notice: 'Applicant type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_applicant_type
      @applicant_type = ApplicantType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def applicant_type_params
      params.require(:applicant_type).permit(:name, :description)
    end
end

app/helpers/applicant_types_helper.rb
module ApplicantTypesHelper
end

app/views/applicant_types/_form.html.erb
<%= simple_form_for(@applicant_type) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/applicant_types/edit.html.erb
<h1>Editing Applicant Type</h1>

<%= render 'form', applicant_type: @applicant_type %>

<%= link_to 'Show', @applicant_type %> |
<%= link_to 'Back', applicant_types_path %>

app/views/applicant_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Applicant Types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @applicant_types.each do |applicant_type| %>
      <tr>
        <td><%= applicant_type.name %></td>
        <td><%= applicant_type.description %></td>
        <td><%= link_to 'Show', applicant_type %></td>
        <td><%= link_to 'Edit', edit_applicant_type_path(applicant_type) %></td>
        <td><%= link_to 'Destroy', applicant_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Applicant Type', new_applicant_type_path %>

app/views/applicant_types/new.html.erb
<h1>New Applicant Type</h1>

<%= render 'form', applicant_type: @applicant_type %>

<%= link_to 'Back', applicant_types_path %>

app/views/applicant_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @applicant_type.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @applicant_type.description %>
</p>

<%= link_to 'Edit', edit_applicant_type_path(@applicant_type) %> |
<%= link_to 'Back', applicant_types_path %>