config/routes.rb
Rails.application.routes.draw do
  resources :appeals
  resources :license_results
  resources :exam_settings
  resources :passing_marks
  resources :applicant_types
  resources :exam_types
  resources :placements do
    collection do
      get 'match'
      get 'publish'
      get 'clear'
      get 'statistics'
    end
  end
  resources :settings
  resources :exams do
    collection do
      get 'import_exam'
      post 'import_exam'
      get 'import_interview'
      post 'import_interview'
      get 'exam_detail'
    end
  end
  resources :timers, path: 'countdown' do
    collection do
      get 'load_deadline'
    end
  end
  resources :application_instructions
  resources :applicant_exam_hubs
  resources :exam_hubs
  resources :regions
  resources :match_results
  resources :events
  resources :academic_years
  resources :universities
  resources :programs
  resources :applicants do
    collection do
      get 'import_applicants'
      post 'import_applicants'
      get 'instructions'
      get 'load_other_university'
      get 'load_disability'
      get 'licensing'
      get 'grade'
      get 'load_attachments'
      get 'university_applicants_by_program'
      get 'applicants_by_program_by_university'
      get 'university_applicants_status_by_program'
      get 'applicants_status'
      get 'publish'
      get 'check_exam'
    end
    member do
      get 'details'
      get 'submit'
    end
  end
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  scope "/admin" do
    resources :users do
      member do
        get 'confirm'
      end
      collection do
        get 'load_institutions'
      end
    end
  end

  authenticated :user do
    root 'home#index', as: :authenticated_root
  end
  get 'home/index'
  get 'home/check_exam_result'
  root to: 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/match_result.rb
class MatchResult < ApplicationRecord
  belongs_to :applicant
  belongs_to :program
  belongs_to :university
end

app/controllers/match_results_controller.rb
class MatchResultsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
  before_action :set_match_result, only: [:show, :edit, :update, :destroy]

  # GET /match_results
  # GET /match_results.json
  def index
    @match_results = MatchResult.all
  end

  # GET /match_results/1
  # GET /match_results/1.json
  def show
  end

  # GET /match_results/new
  def new
    @match_result = MatchResult.new
  end

  # GET /match_results/1/edit
  def edit
  end

  # POST /match_results
  # POST /match_results.json
  def create
    @match_result = MatchResult.new(match_result_params)

    respond_to do |format|
      if @match_result.save
        format.html { redirect_to @match_result, notice: 'Match result was successfully created.' }
        format.json { render :show, status: :created, location: @match_result }
      else
        format.html { render :new }
        format.json { render json: @match_result.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /match_results/1
  # PATCH/PUT /match_results/1.json
  def update
    respond_to do |format|
      if @match_result.update(match_result_params)
        format.html { redirect_to @match_result, notice: 'Match result was successfully updated.' }
        format.json { render :show, status: :ok, location: @match_result }
      else
        format.html { render :edit }
        format.json { render json: @match_result.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /match_results/1
  # DELETE /match_results/1.json
  def destroy
    @match_result.destroy
    respond_to do |format|
      format.html { redirect_to match_results_url, notice: 'Match result was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_match_result
      @match_result = MatchResult.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def match_result_params
      params.require(:match_result).permit(:applicant_id, :program_id, :university_id)
    end
end

app/helpers/match_results_helper.rb
module MatchResultsHelper
end

app/views/match_results/_form.html.erb
<%= simple_form_for(@match_result) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :applicant %>
    <%= f.association :program %>
    <%= f.association :university %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/match_results/edit.html.erb
<h1>Editing Match Result</h1>

<%= render 'form', match_result: @match_result %>

<%= link_to 'Show', @match_result %> |
<%= link_to 'Back', match_results_path %>

app/views/match_results/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Match Results</h1>

<table>
  <thead>
    <tr>
      <th>Applicant</th>
      <th>Program</th>
      <th>University</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @match_results.each do |match_result| %>
      <tr>
        <td><%= match_result.applicant %></td>
        <td><%= match_result.program %></td>
        <td><%= match_result.university %></td>
        <td><%= link_to 'Show', match_result %></td>
        <td><%= link_to 'Edit', edit_match_result_path(match_result) %></td>
        <td><%= link_to 'Destroy', match_result, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Match Result', new_match_result_path %>

app/views/match_results/new.html.erb
<h1>New Match Result</h1>

<%= render 'form', match_result: @match_result %>

<%= link_to 'Back', match_results_path %>

app/views/match_results/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Applicant:</strong>
  <%= @match_result.applicant %>
</p>

<p>
  <strong>Program:</strong>
  <%= @match_result.program %>
</p>

<p>
  <strong>University:</strong>
  <%= @match_result.university %>
</p>

<%= link_to 'Edit', edit_match_result_path(@match_result) %> |
<%= link_to 'Back', match_results_path %>